baseurl = "https://santiago-j-s.github.io/"
theme = "cocoa-eh"
canonifyurls = true
contentdir = "content"
# defaultContentLanguage = "es-AR"
# languageCode = "es-AR"
layoutdir = "layouts"
publishdir = "public"
author = "Santiago Santana"
title = "Santana Santiago"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
locale = "es-AR"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
latestpostcount = 5
github = "santiago-j-s"
email = "santana.santiago@gmail.com"
linkedin = "santiago-santana-22569399"
twitter = "santiago_j_s"
social_banner = "img/banner.png"
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
